services:
  site:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    working_dir: /srv/jekyll
    stdin_open: true
    tty: true
